# Generated by Django 5.0.4 on 2024-06-11 23:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.IntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')])),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=35)),
                ('first_login', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upper_limit', models.IntegerField()),
                ('Lower_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admi',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Evaluated_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=40)),
                ('academic_period', models.CharField(max_length=10)),
                ('student_status', models.BooleanField(default=True)),
                ('course_status', models.BooleanField(default=True)),
                ('user_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_user_teacher', to=settings.AUTH_USER_MODEL)),
                ('user_students', models.ManyToManyField(related_name='courses_user_student', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Por iniciar'), (2, 'Iniciado'), (3, 'Finalizado')])),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('name', models.CharField(max_length=60)),
                ('comment', models.TextField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('comment', models.TextField(max_length=100)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='api.evaluation')),
                ('evaluated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_student', to='api.student')),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_user', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.course')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='api.report'),
        ),
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('Acces_route', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resourses', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('courses', models.ManyToManyField(related_name='rubrics', to='api.course')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='api.scale')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.rubric'),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('scale_description', models.TextField(default=False, null=True)),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='api.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.BigIntegerField()),
                ('evaluationCompleted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluationCompleted', to='api.evaluationcompleted')),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='api.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assigned_project', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='api.course')),
                ('students', models.ManyToManyField(related_name='students', to='api.student')),
            ],
        ),
    ]
