# Generated by Django 5.0.4 on 2024-05-19 00:20

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.IntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')])),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=35)),
                ('first_login', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=40)),
                ('academic_period', models.CharField(max_length=10)),
                ('student_status', models.BooleanField(default=False)),
                ('course_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upper_limit', models.IntegerField()),
                ('Lower_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Admi',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Evaluated_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assigned_project', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='api.course')),
                ('students', models.ManyToManyField(related_name='students', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('Acces_route', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resourses', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='api.rubric')),
            ],
        ),
        migrations.AddField(
            model_name='rubric',
            name='scale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='api.scale'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('standard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='api.standard')),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descriptions', to='api.scale')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=60)),
                ('evaluated', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='api.report')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_student', to='api.student')),
                ('user_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_user', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user_students',
            field=models.ManyToManyField(related_name='courses_user_student', to='api.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='user_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_user_teacher', to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('average', models.DecimalField(decimal_places=3, max_digits=10)),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='api.standard')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='api.evaluation')),
            ],
        ),
    ]
