# Generated by Django 5.0.4 on 2024-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=20)),
                ('name', models.TextField(max_length=60)),
                ('last_name', models.TextField(max_length=60)),
                ('email', models.TextField(max_length=80)),
                ('password', models.TextField(max_length=8)),
            ],
        ),
    ]
