# Generated by Django 5.0.4 on 2024-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='scale_description',
            field=models.TextField(default=False, null=True),
        ),
    ]
