# Generated by Django 5.0.4 on 2024-04-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=20)),
                ('identification', models.IntegerField(max_length=20)),
                ('names', models.TextField(max_length=60)),
                ('last_name', models.TextField(max_length=60)),
                ('email', models.TextField(max_length=80)),
                ('password', models.TextField(max_length=8)),
                ('phone_number', models.IntegerField(verbose_name=20)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Admi',
            new_name='Admin',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='names',
        ),
    ]
