# Generated by Django 5.0.4 on 2024-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admi',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
    ]
