# Generated by Django 5.0.4 on 2024-06-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='scale_description',
            field=models.TextField(default=False, null=True),
        ),
    ]
