# Generated by Django 5.0.4 on 2024-06-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_standard_scale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
