# Generated by Django 5.0.4 on 2024-04-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_rename_admi_admin_rename_name_admin_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identification',
            field=models.IntegerField(),
        ),
    ]
