# Generated by Django 5.0.4 on 2024-04-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacher_identification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('code', models.TextField(max_length=45)),
                ('academic_period', models.TextField(max_length=8)),
            ],
        ),
    ]
