# Generated by Django 5.0.4 on 2024-05-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admi_status_teacher_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
