# Generated by Django 5.0.4 on 2024-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_staff_alter_course_user_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='scale_description',
            field=models.TextField(default=False),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
