# Generated by Django 5.0.4 on 2024-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_student_remove_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
