# Generated by Django 5.0.4 on 2024-05-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_rubric_course_rubric_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='scale_description',
            field=models.TextField(blank=True, default=False),
        ),
    ]
