# Generated by Django 5.0.4 on 2024-04-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_admi_user_alter_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
