# Generated by Django 5.0.4 on 2024-05-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_admi_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')]),
        ),
    ]
