# Generated by Django 5.0.4 on 2024-04-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('project_assigned', models.TextField()),
                ('id_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.course')),
            ],
        ),
    ]
