# Generated by Django 5.0.4 on 2024-05-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
