# Generated by Django 5.0.4 on 2024-04-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gruop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gruop',
            old_name='id_course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='gruop',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.teacher'),
        ),
    ]
