# Generated by Django 5.0.4 on 2024-04-15 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_id_course_gruop_course_gruop_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruop',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacher'),
        ),
    ]
