# Generated by Django 5.0.4 on 2024-04-15 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gruop_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruop',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gropus', to='api.teacher'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=20)),
                ('names', models.TextField(max_length=60)),
                ('last_name', models.TextField(max_length=60)),
                ('email', models.TextField(max_length=80)),
                ('password', models.TextField(max_length=8)),
                ('courses', models.ManyToManyField(related_name='students', to='api.course')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.gruop')),
            ],
        ),
    ]
