# Generated by Django 5.0.4 on 2024-04-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_criteria_scale_evaluation_criteria_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
