# Generated by Django 5.0.4 on 2024-04-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='admin',
            name='names',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_period',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='gruop',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='names',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='names',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
