# Generated by Django 5.0.4 on 2024-04-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_admin_code_alter_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='identification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
